title: Fajny CSS
email: julien.sebag@me.com
description: Documentation for Fajny CSS. Build responsive web projects with Fajny CSS, a simple and lightweight SCSS Framework with a lot of components.
baseurl: "/"
url: "http://fajny-css.github.io"
github_username: JulSeb42

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

collections:
  basics:
    output: true
  components:
    output: true
  helpers:
    output: true
  icons:
    output: false
  styles:
    output: true
